# Generated by Django 5.0.14 on 2026-03-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Programming, Music, Cooking', max_length=50),
        ),
    ]
