# Generated by Django 5.0.14 on 2026-03-30 23:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_swaprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swaprequest',
            unique_together={('sender', 'skill')},
        ),
    ]
