# Generated by Django 5.0.14 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_alter_swaprequest_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=9,
            ),
        ),
    ]
