# Generated by Django 5.0.14 on 2026-02-20 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='A brief headline about your skills or interests.', max_length=100)),
                ('experience_level', models.CharField(choices=[('BEG', 'Beiginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('EXP', 'Expert')], default='BEG', help_text='Select your experience level', max_length=3)),
                ('bio', models.TextField(blank=True, help_text='A detailed description of your skills and interests.')),
                ('location', models.CharField(blank=True, help_text='e.g., Milwaukee, WI', max_length=100)),
                ('skills_offered', models.TextField(blank=True, help_text='List the skills you can offer')),
                ('skills_wanted', models.TextField(blank=True, help_text='List the skills you are looking to learn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
