# Generated by Django 5.0.14 on 2026-04-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_location'),
        ('profiles', '0003_profile_banner_image_profile_profile_image'),
    ]

    operations = [
    ]
